name: Simple
run-name: Simple_${{inputs.guid}}
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'
        required: true
      guid:
        type: string
        default: "N/A"
jobs:
  simple-input-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message
        run: |
         SUMMARY=$'# Testing Job Summary\n## Second Level Heading\nHello GitHub'
         echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
